image: go1.3
git:
  path: github.com/npateriya/logspout
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - find . 
  - go get .
  - make build/logspout
  - make stage/logspout
  - find . 
publish:
  docker: 
    dockerfile: ./Dockerfile
    docker_host: 172.16.42.1
    docker_port: 2375
    registry_login: true
    username: npateriyainsecure
    password: githubpassword
    email: npateriya@yahoo.com
    image_name: logspout
    push_latest: true

